version: "3"
services: 
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    networks:
      - my_network

  server:
    build: ./api
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - server

networks:
  my_network:
    driver: bridge